#!/bin/bash

set -e

export TAG=$1

if [[ $TAG == "" ]]; then
  echo "missing version tag"
  exit 1
fi

GOOS=linux go build

docker build -t slofurno/kubestat-ui -t slofurno/kubestat-ui:$TAG .
docker push slofurno/kubestat-ui:$TAG
