apiVersion: apps/v1beta2
kind: DaemonSet
metadata:
  name: kubestat
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: kubestat
  template:
    metadata:
      labels:
        name: kubestat
    spec:
      tolerations:
        - key: "target"
          operator: "Exists"
      volumes:
        - name: node-meminfo
          hostPath:
            path: /proc/meminfo
        - name: node-stat
          hostPath:
            path: /proc/stat
        - name: node-sys
          hostPath:
            path: /sys
      containers:
      - name: kubestat
        image: slofurno/kubestat:v0.5.2
        command: ["/kubestat"]
        args: ["--root=/node-sys/fs/cgroup"]
        env:
          - name: DRAIN_ENDPOINT
            value: "http://s.gdf3.com:9090/stats"
        volumeMounts:
          - mountPath: /node-meminfo
            name: node-meminfo
          - mountPath: /node-stat
            name: node-stat
          - mountPath: /node-sys
            name: node-sys
            readOnly: true
